#!/bin/bash
# install_mitm_certs.sh

# Certificate file path (generated by mitmproxy in step 1 of the main script)
CERT_PATH=~/.mitmproxy/mitmproxy-ca-cert.pem

if [ ! -f "$CERT_PATH" ]; then
    echo "Error: mitmproxy certificate not found at $CERT_PATH. Cannot install."
    exit 1
fi

echo "Installing certificate from $CERT_PATH..."

# 1. System-wide Installation (Debian/Ubuntu/Apt-based)
# This requires sudo and is the most common way to get it recognized by many apps.
if command -v update-ca-certificates &> /dev/null; then
    echo "Attempting system-wide installation (requires sudo)..."
    sudo cp "$CERT_PATH" /usr/local/share/ca-certificates/mitmproxy-ca.crt
    sudo update-ca-trust
    echo "System-wide installation finished."
else
    echo "Skipping system-wide install: 'update-ca-certificates' not found."
fi

# 2. Chromium/NSS Database Installation
# Chromium uses the NSS database for its certificate store.
# This assumes the default profile path and requires 'certutil'.

NSS_DB_PATH=~/.pki/nssdb
if [ ! -d "$NSS_DB_PATH" ]; then
    echo "NSS database not found at $NSS_DB_PATH. Creating directory..."
    mkdir -p "$NSS_DB_PATH"
fi

if command -v certutil &> /dev/null; then
    echo "Attempting to install into NSS database at $NSS_DB_PATH..."
    # C: Trust for authenticating SSL clients
    # T: Trust for authenticating SSL servers
    # P: Trust for signing code
    certutil -A -n "mitmproxy CA" -t "CT,," -i "$CERT_PATH" -d "sql:$NSS_DB_PATH"
    if [ $? -eq 0 ]; then
        echo "Certificate successfully added to NSS database."
    else
        echo "Warning: 'certutil' failed to add certificate (it may already be present)."
    fi
else
    echo "Skipping NSS database install: 'certutil' not found. Install 'libnss3-tools'."
fi
